package com.selxo.rougo.windows

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.net.HttpURLConnection
import java.net.URI
import java.net.URL
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.util.Locale
import java.util.UUID
import java.util.concurrent.CompletableFuture
import java.util.concurrent.TimeUnit
import kotlin.math.roundToInt

data class YoutubeSubtitleChoice(
    val label: String,
    val languageCode: String,
    val isAutoGenerated: Boolean
)

data class YoutubeStreamFormat(
    val formatId: String?,
    val formatNote: String?,
    val ext: String?,
    val vcodec: String?,
    val acodec: String?,
    val height: Int,
    val tbr: Int,
    val url: String?,
    val manifestUrl: String?,
    val protocol: String?
)

data class YoutubeSetupData(
    val title: String,
    val fallbackUrl: String?,
    val formats: List<YoutubeStreamFormat>,
    val subtitleChoices: List<YoutubeSubtitleChoice>,
    val thumbnailUrl: String? = null,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)

data class FastYoutubeStream(
    val title: String,
    val streamUrl: String,
    val formatId: String?,
    val isVideo: Boolean,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)

data class ResolvedMediaStream(
    val url: String,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)

data class YoutubePlaylistImportData(
    val title: String,
    val entries: List<PlaylistImportEntry>
)

data class ProcessResult(
    val exitCode: Int,
    val output: String,
    val timedOut: Boolean = false
)

object MediaTools {
    private val toolsDir = File(WindowsPaths.appDir, "tools").also { it.mkdirs() }
    private val ytdlpExe = File(toolsDir, "yt-dlp.exe")

    suspend fun ensureReady(onStatus: (String) -> Unit = {}): Boolean = withContext(Dispatchers.IO) {
        try {
            ensureYtDlp(onStatus)
            if (ffmpegCommand() == null || ffprobeCommand() == null) {
                onStatus("Bundled FFmpeg was not found. Waveform and metadata extraction need the packaged build.")
            }
            true
        } catch (t: Throwable) {
            CrashReporter.recordHandled("MediaTools.ensureReady", t)
            false
        }
    }

    fun ytDlpCommand(): String? =
        bundledTool("yt-dlp.exe")?.absolutePath
            ?: ytdlpExe.takeIf { it.isFile }?.absolutePath
            ?: findOnPath("yt-dlp.exe")
            ?: findOnPath("yt-dlp")

    fun ffmpegCommand(): String? =
        bundledTool("ffmpeg/ffmpeg.exe")?.absolutePath ?: findOnPath("ffmpeg.exe") ?: findOnPath("ffmpeg")

    fun ffprobeCommand(): String? =
        bundledTool("ffmpeg/ffprobe.exe")?.absolutePath ?: findOnPath("ffprobe.exe") ?: findOnPath("ffprobe")

    fun rnnoiseModelFile(): File? =
        bundledTool("rnnoise/std.rnnn")?.takeIf { it.isFile }

    fun vlcNativeDir(): File? =
        bundledTool("vlc/libvlc.dll")?.parentFile
            ?: File("C:/Program Files/VideoLAN/VLC").takeIf { File(it, "libvlc.dll").isFile }
            ?: File("C:/Program Files (x86)/VideoLAN/VLC").takeIf { File(it, "libvlc.dll").isFile }

    private fun ensureYtDlp(onStatus: (String) -> Unit) {
        if (bundledTool("yt-dlp.exe")?.isFile == true) return
        val pathCommand = findOnPath("yt-dlp.exe") ?: findOnPath("yt-dlp")
        if (pathCommand != null && !ytdlpExe.isFile) return

        val lastUpdate = Prefs.app.getLong("last_ytdlp_update", 0L)
        val shouldDownload = !ytdlpExe.isFile || System.currentTimeMillis() - lastUpdate > 24 * 60 * 60 * 1000L
        if (!shouldDownload) return

        onStatus("Downloading yt-dlp...")
        val tmp = File(toolsDir, "yt-dlp.exe.tmp")
        val connection = URL("https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe")
            .openConnection() as HttpURLConnection
        connection.requestMethod = "GET"
        connection.connectTimeout = 30_000
        connection.readTimeout = 120_000
        connection.inputStream.use { input ->
            tmp.outputStream().use { output -> input.copyTo(output) }
        }
        Files.move(tmp.toPath(), ytdlpExe.toPath(), StandardCopyOption.REPLACE_EXISTING)
        Prefs.app.putLong("last_ytdlp_update", System.currentTimeMillis())
        onStatus("")
    }

    private fun bundledTool(relativePath: String): File? {
        val root = System.getProperty("compose.application.resources.dir")
            ?.takeIf { it.isNotBlank() }
            ?.let(::File)
            ?: return null
        return File(root, "tools/$relativePath").takeIf { it.isFile }
    }

    private fun findOnPath(name: String): String? {
        val path = System.getenv("PATH") ?: return null
        val separator = File.pathSeparator
        return path.split(separator)
            .asSequence()
            .map { File(it, name) }
            .firstOrNull { it.isFile && it.canExecute() }
            ?.absolutePath
    }
}

fun runProcess(command: List<String>, timeoutSeconds: Long = 120): ProcessResult {
    return try {
        val process = ProcessBuilder(command)
            .redirectErrorStream(true)
            .start()
        val outputFuture = CompletableFuture.supplyAsync {
            process.inputStream.bufferedReader(Charsets.UTF_8).use { it.readText() }
        }
        val completed = process.waitFor(timeoutSeconds, TimeUnit.SECONDS)
        if (!completed) {
            process.destroyForcibly()
            ProcessResult(-1, outputFuture.get(2, TimeUnit.SECONDS), timedOut = true)
        } else {
            ProcessResult(process.exitValue(), outputFuture.get(2, TimeUnit.SECONDS))
        }
    } catch (t: Throwable) {
        ProcessResult(-1, t.message.orEmpty())
    }
}

fun playableYoutubeUrl(url: String): String? {
    val uri = runCatching { URI(url) }.getOrNull() ?: return null
    val host = uri.host.orEmpty().lowercase(Locale.US)
    val segments = uri.path.orEmpty().trim('/').split('/').filter { it.isNotBlank() }
    val hasVideoId = when {
        host == "youtu.be" || host.endsWith(".youtu.be") -> segments.firstOrNull()?.isNotBlank() == true
        host.contains("youtube.com") -> {
            uri.rawQuery.orEmpty().split('&').any { it.substringBefore('=') == "v" && it.substringAfter('=', "").isNotBlank() } ||
                (segments.size >= 2 && segments[0] in setOf("shorts", "live", "embed") && segments[1].isNotBlank())
        }
        else -> false
    }
    return if (hasVideoId) url else null
}

fun youtubeThumbnailUrl(sourceUrl: String?): String? {
    val id = youtubeVideoId(sourceUrl) ?: return null
    return "https://img.youtube.com/vi/$id/hqdefault.jpg"
}

private fun youtubeVideoId(sourceUrl: String?): String? {
    if (sourceUrl.isNullOrBlank()) return null
    val uri = runCatching { URI(sourceUrl) }.getOrNull() ?: return null
    val host = uri.host.orEmpty().lowercase(Locale.US)
    val segments = uri.path.orEmpty().trim('/').split('/').filter { it.isNotBlank() }
    return when {
        host.contains("youtu.be") -> segments.firstOrNull()
        host.contains("youtube.com") -> {
            uri.rawQuery.orEmpty().split('&').firstOrNull { it.substringBefore('=') == "v" }?.substringAfter('=', "")
                ?: if (segments.size >= 2 && segments[0] in setOf("shorts", "live", "embed")) segments[1] else null
        }
        else -> null
    }?.takeIf { it.isNotBlank() }
}

fun youtubeBrowserOpenableUrl(url: String): String? =
    playableYoutubeUrl(url)?.takeIf { isYoutubeUrl(it) }
        ?: url.takeIf { isYoutubePlaylistUrl(it) }

fun youtubeBrowserInterceptScript(): String {
    return """
        (function() {
            if (window.__rougoYoutubeBridgeInstalled) return;
            window.__rougoYoutubeBridgeInstalled = true;

            function isRougoYoutubeUrl(rawUrl) {
                try {
                    var url = new URL(rawUrl, window.location.href);
                    var host = url.hostname.toLowerCase();
                    var path = url.pathname || "";
                    return ((host === "youtu.be" || host.endsWith(".youtu.be")) && path.length > 1) ||
                        (host.indexOf("youtube.com") !== -1 &&
                            (url.searchParams.get("v") || url.searchParams.get("list") || /^\/(shorts|live|embed|playlist)\//.test(path)));
                } catch (e) {
                    return false;
                }
            }

            function openInRougo(rawUrl) {
                if (!isRougoYoutubeUrl(rawUrl) || !window.RougoYoutube) return false;
                window.RougoYoutube.openYoutubeUrl(new URL(rawUrl, window.location.href).href);
                return true;
            }

            document.addEventListener("click", function(event) {
                var node = event.target;
                while (node && node.tagName !== "A") node = node.parentElement;
                if (node && node.href && openInRougo(node.href)) {
                    event.preventDefault();
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                }
            }, true);

            var pushState = history.pushState;
            history.pushState = function() {
                var result = pushState.apply(this, arguments);
                setTimeout(function() { openInRougo(window.location.href); }, 0);
                return result;
            };

            var replaceState = history.replaceState;
            history.replaceState = function() {
                var result = replaceState.apply(this, arguments);
                setTimeout(function() { openInRougo(window.location.href); }, 0);
                return result;
            };

            window.addEventListener("popstate", function() {
                setTimeout(function() { openInRougo(window.location.href); }, 0);
            });

            openInRougo(window.location.href);
        })();
    """.trimIndent()
}

fun fetchFastYoutubeStream(url: String, preferredResolution: String): FastYoutubeStream? {
    val command = MediaTools.ytDlpCommand() ?: return null
    val format = fastYoutubeFormatSelector(preferredResolution)
    val result = runProcess(
        listOf(command, "--no-playlist", "--dump-json", "-f", format, url),
        timeoutSeconds = 90
    )
    if (result.exitCode != 0) return null
    val json = JSONObject(extractDumpedJson(result.output))
    val formats = parseYoutubeFormats(json)
    val selected = selectPreferredYoutubeFormat(formats, preferredResolution)
    val streamUrl = selected?.bestPlaybackUrl() ?: json.optString("url").takeIf { it.isNotBlank() } ?: return null
    val headers = parseStreamHttpHeaders(json)
    return FastYoutubeStream(
        title = cleanYtdlpTitle(json.optString("title"), url) ?: sourceDefaultTitle(url),
        streamUrl = streamUrl,
        formatId = selected?.formatId ?: json.optString("format_id").takeIf { it.isNotBlank() },
        isVideo = selected?.isVlcFriendlyVideoFormat() ?: true,
        httpUserAgent = headers.first,
        httpReferer = headers.second
    )
}

fun createFastYoutubeLibraryItem(stream: FastYoutubeStream, sourceUrl: String): LibraryItem {
    val itemId = UUID.randomUUID().toString()
    val coverArtPath = youtubeThumbnailUrl(sourceUrl)?.let { downloadRemoteCover(itemId, it) }
    cacheResolvedStreamUrl(sourceUrl, stream.formatId, stream.streamUrl)
    return LibraryItem(
        id = itemId,
        title = stream.title,
        mediaUri = stream.streamUrl,
        subtitleUri = null,
        progress = 0L,
        duration = 0L,
        isVideo = stream.isVideo,
        sourceUrl = sourceUrl,
        formatId = stream.formatId,
        coverArtPath = coverArtPath,
        httpUserAgent = stream.httpUserAgent,
        httpReferer = stream.httpReferer
    )
}

fun fetchYoutubeSetupData(url: String): YoutubeSetupData {
    val json = fetchYoutubeInfoJson(url)
    val headers = parseStreamHttpHeaders(json)
    return YoutubeSetupData(
        title = cleanYtdlpTitle(json.optString("title"), url) ?: sourceDefaultTitle(url),
        fallbackUrl = json.optString("url").takeIf { it.isNotBlank() },
        formats = parseYoutubeFormats(json),
        subtitleChoices = parseYoutubeSubtitleChoices(json),
        thumbnailUrl = bestThumbnailUrl(json) ?: youtubeThumbnailUrl(url),
        httpUserAgent = headers.first,
        httpReferer = headers.second
    )
}

fun fetchYoutubeSubtitleChoices(url: String): List<YoutubeSubtitleChoice> {
    val command = MediaTools.ytDlpCommand() ?: return emptyList()
    val result = runProcess(
        listOf(command, "--no-playlist", "--skip-download", "--list-subs", "--no-warnings", url),
        timeoutSeconds = 25
    )
    if (result.exitCode != 0 || result.timedOut) return emptyList()
    return parseYoutubeSubtitleListOutput(result.output)
}

fun fetchYoutubePlaylistImportData(url: String): YoutubePlaylistImportData? {
    val command = MediaTools.ytDlpCommand() ?: return null
    val result = runProcess(
        listOf(command, "--flat-playlist", "--dump-single-json", url),
        timeoutSeconds = 120
    )
    if (result.exitCode != 0) return null
    return parseYoutubePlaylistImportData(JSONObject(extractDumpedJson(result.output)))
        .takeIf { it.entries.isNotEmpty() }
}

fun parseYoutubePlaylistImportData(json: JSONObject): YoutubePlaylistImportData {
    val title = firstCleanMetadataValue(
        cleanMetadataValue(json.optString("title")),
        cleanMetadataValue(json.optString("playlist_title"))
    ) ?: "Playlist"
    val entriesJson = json.optJSONArray("entries") ?: JSONArray()
    val entries = buildList {
        for (i in 0 until entriesJson.length()) {
            val entry = entriesJson.optJSONObject(i) ?: continue
            val sourceUrl = youtubePlaylistEntrySourceUrl(entry) ?: continue
            add(
                PlaylistImportEntry(
                    title = firstCleanMetadataValue(
                        cleanMetadataValue(entry.optString("title")),
                        cleanMetadataValue(entry.optString("fulltitle"))
                    ) ?: "Video ${size + 1}",
                    sourceUrl = sourceUrl,
                    thumbnailUrl = bestThumbnailUrl(entry) ?: youtubeThumbnailUrl(sourceUrl),
                    durationMs = entry.optLong("duration", 0L).takeIf { it > 0L }?.times(1000L) ?: 0L,
                    index = entry.optInt("playlist_index", i)
                )
            )
        }
    }
    return YoutubePlaylistImportData(title, entries.distinctBy { it.sourceUrl })
}

private fun youtubePlaylistEntrySourceUrl(entry: JSONObject): String? {
    val directUrl = entry.optString("url").takeIf { it.startsWith("http", ignoreCase = true) }
    if (directUrl != null) return directUrl
    val webpageUrl = entry.optString("webpage_url").takeIf { it.startsWith("http", ignoreCase = true) }
    if (webpageUrl != null) return webpageUrl
    val id = entry.optString("id").takeIf { it.isNotBlank() } ?: return null
    return "https://www.youtube.com/watch?v=$id"
}

fun createYoutubeLibraryItem(
    setupData: YoutubeSetupData,
    format: YoutubeStreamFormat,
    subtitlePath: String?,
    sourceUrl: String
): LibraryItem {
    val itemId = UUID.randomUUID().toString()
    val mediaUrl = format.bestPlaybackUrl() ?: setupData.fallbackUrl ?: sourceUrl
    cacheResolvedStreamUrl(sourceUrl, format.formatId, mediaUrl)
    val coverArtPath = setupData.thumbnailUrl?.let { downloadRemoteCover(itemId, it) }
    return LibraryItem(
        id = itemId,
        title = setupData.title,
        mediaUri = mediaUrl,
        subtitleUri = subtitlePath,
        progress = 0L,
        duration = 0L,
        isVideo = format.isVlcFriendlyVideoFormat(),
        sourceUrl = sourceUrl,
        formatId = format.formatId,
        coverArtPath = coverArtPath,
        httpUserAgent = setupData.httpUserAgent,
        httpReferer = setupData.httpReferer
    )
}

fun selectPreferredYoutubeSubtitle(
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): YoutubeSubtitleChoice? {
    return preferredYoutubeSubtitleChoices(choices, preferredLanguage).firstOrNull()
}

fun downloadPreferredYoutubeSubtitle(
    url: String,
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): String? {
    preferredYoutubeSubtitleChoices(choices, preferredLanguage).forEach { choice ->
        val subtitle = downloadYoutubeSubtitle(url, choice.languageCode, choice.isAutoGenerated)
        if (subtitle != null) return subtitle
    }
    return null
}

fun preferredYoutubeSubtitleChoices(
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): List<YoutubeSubtitleChoice> {
    if (choices.isEmpty()) return emptyList()
    if (preferredLanguage == "any") return choices
    val normalized = preferredLanguage.lowercase(Locale.US)
    val preferredChoice = choices.firstOrNull { choice ->
        val code = choice.languageCode.lowercase(Locale.US)
        code == normalized || code.startsWith("$normalized-")
    } ?: choices.first()
    val preferredLanguageMatches = choices.filter { choice ->
        val code = choice.languageCode.lowercase(Locale.US)
        code == normalized || code.startsWith("$normalized-")
    }
    return (listOf(preferredChoice) +
        choices.filter { it.languageCode == preferredChoice.languageCode } +
        preferredLanguageMatches +
        choices.take(2))
        .distinctBy { "${it.languageCode}:${it.isAutoGenerated}" }
}

fun selectPreferredYoutubeFormat(
    formats: List<YoutubeStreamFormat>,
    preferredResolution: String
): YoutubeStreamFormat? {
    val playable = formats.filter { it.bestPlaybackUrl() != null }
    val audioFormats = playable
        .filter { it.vcodec == "none" && it.acodec != "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { if (it.isVlcFriendlyAudioFormat()) 1 else 0 }.thenByDescending { it.tbr }.thenByDescending { it.formatId ?: "" })
    val videoFormats = playable
        .filter { it.vcodec != "none" && it.acodec != "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { it.height }.thenByDescending { if (it.isVlcFriendlyVideoFormat()) 1 else 0 }.thenByDescending { it.tbr })

    return when (preferredResolution) {
        YOUTUBE_RESOLUTION_AUDIO -> audioFormats.firstOrNull() ?: videoFormats.firstOrNull()
        YOUTUBE_RESOLUTION_HIGHEST -> videoFormats.firstOrNull() ?: audioFormats.firstOrNull()
        else -> {
            val targetHeight = preferredResolution.toIntOrNull()
            if (targetHeight == null) {
                videoFormats.firstOrNull() ?: audioFormats.firstOrNull()
            } else {
                videoFormats.firstOrNull { it.height in 1..targetHeight }
                    ?: videoFormats.lastOrNull()
                    ?: audioFormats.firstOrNull()
            }
        }
    }
}

fun resolveYoutubeStreamUrl(url: String, formatId: String?): String? =
    resolveYoutubeMediaStream(url, formatId)?.url

fun resolveYoutubeMediaStream(
    url: String,
    formatId: String?,
    preferredResolution: String = DEFAULT_YOUTUBE_RESOLUTION
): ResolvedMediaStream? {
    val resolvedFormatId = formatId.takeUnless { isKnownYoutubeVideoOnlyFormatId(it) }
    cachedResolvedStreamUrl(url, resolvedFormatId)?.let { return ResolvedMediaStream(it) }
    val command = MediaTools.ytDlpCommand() ?: return null
    val args = buildList {
        add(command)
        add("--no-playlist")
        resolvedFormatId?.takeIf { it.isNotBlank() }?.let {
            add("-f")
            add(it)
        } ?: run {
            add("-f")
            add(fastYoutubeFormatSelector(preferredResolution))
        }
        add("--dump-json")
        add(url)
    }
    val result = runProcess(args, timeoutSeconds = 90)
    if (result.exitCode != 0) return null
    val json = runCatching { JSONObject(extractDumpedJson(result.output)) }.getOrNull() ?: return null
    val headers = parseStreamHttpHeaders(json)
    val formats = parseYoutubeFormats(json)
    val selected = resolvedFormatId
        ?.let { id -> formats.firstOrNull { it.formatId == id } }
        ?: selectPreferredYoutubeFormat(formats, preferredResolution)
    val resolved = json.optString("url").takeIf { it.startsWith("http", ignoreCase = true) }
        ?: selected?.bestPlaybackUrl()
        ?: return null
    cacheResolvedStreamUrl(url, resolvedFormatId, resolved)
    return ResolvedMediaStream(resolved, headers.first, headers.second)
}

fun invalidateResolvedStreamUrl(url: String, formatId: String?) {
    val resolvedFormatId = formatId.takeUnless { isKnownYoutubeVideoOnlyFormatId(it) }
    StreamUrlCache.remove(streamUrlCacheKey(url, resolvedFormatId))
}

fun downloadYoutubeSubtitle(url: String, languageCode: String, isAutoGenerated: Boolean): String? {
    if (!isYoutubeUrl(url)) return null
    val command = MediaTools.ytDlpCommand() ?: return null
    val fileId = UUID.randomUUID().toString().replace(Regex("[^A-Za-z0-9_-]"), "_")
    val outputTemplate = File(WindowsPaths.subtitlesDir, "$fileId.%(ext)s").absolutePath
    val args = buildList {
        add(command)
        add("--no-playlist")
        add("--skip-download")
        if (isAutoGenerated) add("--write-auto-subs") else add("--write-subs")
        add("--sub-langs")
        add(languageCode)
        add("--sub-format")
        add("vtt/srt/best")
        add("-o")
        add(outputTemplate)
        add(url)
    }
    val result = runProcess(args, timeoutSeconds = 90)
    if (result.exitCode != 0) {
        return if (!isAutoGenerated) downloadYoutubeSubtitle(url, languageCode, true) else null
    }
    val subtitle = WindowsPaths.subtitlesDir.listFiles()
        ?.filter { it.isFile && it.name.startsWith(fileId) && it.extension.lowercase(Locale.US) in setOf("vtt", "srt", "ass") }
        ?.maxByOrNull { it.lastModified() }
        ?.absolutePath
    return subtitle ?: if (!isAutoGenerated) downloadYoutubeSubtitle(url, languageCode, true) else null
}

fun downloadVideoLinkToLibraryItem(
    url: String,
    existingItem: LibraryItem? = null,
    onProgress: (String) -> Unit = {}
): LibraryItem? {
    val command = MediaTools.ytDlpCommand() ?: return null
    val itemId = existingItem?.id ?: UUID.randomUUID().toString()
    val fileId = itemId.replace(Regex("[^A-Za-z0-9_-]"), "_")
    val outputTemplate = File(WindowsPaths.downloadsDir, "$fileId.%(ext)s").absolutePath
    onProgress("Downloading ${streamSourceLabel(url)} video...")
    val result = runProcess(
        listOf(
            command,
            "--no-playlist",
            "--newline",
            "--embed-metadata",
            "--write-thumbnail",
            "-f",
            "bestvideo[height<=720]+bestaudio/best[height<=720]/best",
            "--merge-output-format",
            "mp4",
            "-o",
            outputTemplate,
            url
        ),
        timeoutSeconds = 60 * 60
    )
    if (result.exitCode != 0) {
        onProgress("${streamSourceLabel(url)} download failed.")
        DesktopNotifier.warning("Download failed", "${streamSourceLabel(url)} download failed.")
        return null
    }
    val mediaFile = WindowsPaths.downloadsDir.listFiles()
        ?.filter { it.isFile && it.name.startsWith(fileId) && it.extension.lowercase(Locale.US) !in setOf("jpg", "jpeg", "png", "webp", "vtt", "srt") }
        ?.maxByOrNull { it.lastModified() }
        ?: return null
    val metadata = extractMediaMetadata(mediaFile.absolutePath, itemId, isVideoFile(mediaFile))
    val title = cleanMetadataValue(metadata.title) ?: existingItem?.title ?: mediaFile.nameWithoutExtension
    val cover = metadata.coverArtPath ?: WindowsPaths.downloadsDir.listFiles()
        ?.firstOrNull { it.isFile && it.name.startsWith(fileId) && it.extension.lowercase(Locale.US) in setOf("jpg", "jpeg", "png", "webp") }
        ?.absolutePath
    onProgress("")
    DesktopNotifier.info("Download complete", title)
    return (existingItem ?: LibraryItem(
        id = itemId,
        title = title,
        mediaUri = mediaFile.absolutePath,
        subtitleUri = null,
        progress = 0L,
        duration = metadata.durationMs ?: 0L,
        isVideo = isVideoFile(mediaFile),
        sourceUrl = url,
        coverArtPath = cover
    )).copy(
        title = title,
        mediaUri = mediaFile.absolutePath,
        duration = metadata.durationMs ?: existingItem?.duration ?: 0L,
        isVideo = isVideoFile(mediaFile),
        sourceUrl = existingItem?.sourceUrl ?: url,
        coverArtPath = cover ?: existingItem?.coverArtPath
    )
}

fun initialPlayableMediaUri(item: LibraryItem): String? {
    if (item.hasLegacyYoutubeVideoOnlyFormat()) return null
    val mediaUri = item.mediaUri.trim()
    if (mediaUri.isBlank()) return null
    if (item.sourceUrl == null) return mediaUri
    if (item.hasDownloadedLocalCopy()) return item.mediaUri
    if (mediaUri != item.sourceUrl.trim()) {
        if (isYoutubeUrl(item.sourceUrl) && isExpiredYoutubeDirectStreamUrl(mediaUri)) return null
        return mediaUri
    }
    return null
}

fun extractMediaMetadata(path: String, itemId: String, isVideo: Boolean): MediaMetadataSnapshot {
    val ffprobe = MediaTools.ffprobeCommand()
    if (ffprobe != null) {
        val result = runProcess(
            listOf(ffprobe, "-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", path),
            timeoutSeconds = 30
        )
        if (result.exitCode == 0 && result.output.isNotBlank()) {
            runCatching {
                val json = JSONObject(result.output)
                val format = json.optJSONObject("format") ?: JSONObject()
                val tags = format.optJSONObject("tags") ?: JSONObject()
                val durationMs = format.optDouble("duration", 0.0).takeIf { it > 0.0 }?.times(1000.0)?.roundToInt()?.toLong()
                val coverPath = extractAttachedPictureWithFfmpeg(path, itemId)
                return MediaMetadataSnapshot(
                    title = tags.optCleanString("title"),
                    artist = tags.optCleanString("artist"),
                    album = tags.optCleanString("album"),
                    albumArtist = tags.optCleanString("album_artist") ?: tags.optCleanString("albumartist"),
                    genre = tags.optCleanString("genre"),
                    year = tags.optCleanString("date") ?: tags.optCleanString("year"),
                    durationMs = durationMs,
                    coverArtPath = coverPath
                )
            }.onFailure {
                CrashReporter.recordHandled("extractMediaMetadata.ffprobe", it)
            }
        }
    }
    return MediaMetadataSnapshot(
        title = File(path).nameWithoutExtension,
        durationMs = null,
        coverArtPath = if (isVideo) null else null
    )
}

private fun extractAttachedPictureWithFfmpeg(path: String, itemId: String): String? {
    val ffmpeg = MediaTools.ffmpegCommand() ?: return null
    val target = File(WindowsPaths.coversDir, "${itemId.replace(Regex("[^A-Za-z0-9_-]"), "_")}.jpg")
    val result = runProcess(
        listOf(ffmpeg, "-y", "-i", path, "-an", "-vcodec", "mjpeg", "-frames:v", "1", target.absolutePath),
        timeoutSeconds = 30
    )
    return target.takeIf { result.exitCode == 0 && it.isFile && it.length() > 0L }?.absolutePath
}

fun mergeMetadataIntoItem(item: LibraryItem, metadata: MediaMetadataSnapshot, fallbackTitle: String = item.title): LibraryItem {
    return item.copy(
        title = metadata.title ?: fallbackTitle,
        artist = metadata.artist ?: item.artist,
        album = metadata.album ?: item.album,
        albumArtist = metadata.albumArtist ?: item.albumArtist,
        genre = metadata.genre ?: item.genre,
        year = metadata.year ?: item.year,
        duration = metadata.durationMs ?: item.duration,
        coverArtPath = metadata.coverArtPath ?: item.coverArtPath
    )
}

fun downloadRemoteCover(itemId: String, url: String): String? {
    return runCatching {
        val ext = url.substringBefore('?').substringAfterLast('.', "jpg").takeIf { it.length in 2..5 } ?: "jpg"
        val target = File(WindowsPaths.coversDir, "${itemId.replace(Regex("[^A-Za-z0-9_-]"), "_")}.$ext")
        URL(url).openStream().use { input ->
            target.outputStream().use { output -> input.copyTo(output) }
        }
        target.absolutePath
    }.getOrElse {
        CrashReporter.recordHandled("downloadRemoteCover", it)
        null
    }
}

private fun fetchYoutubeInfoJson(url: String): JSONObject {
    val command = MediaTools.ytDlpCommand() ?: error("yt-dlp is not available")
    val result = runProcess(listOf(command, "--no-playlist", "--dump-single-json", url), timeoutSeconds = 120)
    if (result.exitCode != 0) error(result.output.ifBlank { "yt-dlp failed" })
    return JSONObject(extractDumpedJson(result.output))
}

private fun fastYoutubeFormatSelector(preferredResolution: String): String = when (preferredResolution) {
    YOUTUBE_RESOLUTION_AUDIO -> "bestaudio[ext=m4a]/bestaudio/best"
    YOUTUBE_RESOLUTION_HIGHEST -> "best[vcodec!=none][acodec!=none][ext=mp4]/best[vcodec!=none][acodec!=none]/best"
    YOUTUBE_RESOLUTION_ASK -> "best[vcodec!=none][acodec!=none][height<=720][ext=mp4]/best[vcodec!=none][acodec!=none][height<=720]/best"
    else -> {
        val h = preferredResolution.toIntOrNull() ?: 720
        "best[vcodec!=none][acodec!=none][height<=$h][ext=mp4]/best[vcodec!=none][acodec!=none][height<=$h]/best"
    }
}

private fun sourceDefaultTitle(url: String): String = "${streamSourceLabel(url)} Video"

private fun cleanYtdlpTitle(value: String?, sourceUrl: String): String? {
    val cleaned = cleanMetadataValue(value)
    return cleaned?.takeIf { !looksLikeGeneratedFileId(it) && !it.equals(sourceDefaultTitle(sourceUrl), ignoreCase = true) }
}

fun looksLikeGeneratedFileId(value: String): Boolean = value.matches(Regex("[A-Za-z0-9_-]{8,}"))

private fun parseStreamHttpHeaders(json: JSONObject): Pair<String?, String?> {
    val headers = json.optJSONObject("http_headers") ?: JSONObject()
    val userAgent = headers.optCleanString("User-Agent")
        ?: headers.optCleanString("user-agent")
        ?: json.optCleanString("user_agent")
    val referer = headers.optCleanString("Referer")
        ?: headers.optCleanString("referer")
        ?: headers.optCleanString("Referrer")
    return userAgent to referer
}

private fun bestThumbnailUrl(json: JSONObject): String? {
    val thumbnails = json.optJSONArray("thumbnails") ?: return json.optString("thumbnail").takeIf { it.isNotBlank() }
    var best: JSONObject? = null
    for (i in 0 until thumbnails.length()) {
        val candidate = thumbnails.optJSONObject(i) ?: continue
        if (candidate.optString("url").isBlank()) continue
        if (best == null || candidate.optInt("width", 0) * candidate.optInt("height", 0) > best!!.optInt("width", 0) * best!!.optInt("height", 0)) {
            best = candidate
        }
    }
    return best?.optString("url")?.takeIf { it.isNotBlank() } ?: json.optString("thumbnail").takeIf { it.isNotBlank() }
}

private fun extractDumpedJson(output: String): String {
    val trimmed = output.trim()
    if (trimmed.startsWith("{")) return trimmed
    val start = trimmed.indexOf('{')
    val end = trimmed.lastIndexOf('}')
    return if (start >= 0 && end > start) trimmed.substring(start, end + 1) else trimmed
}

private fun parseYoutubeSubtitleChoices(json: JSONObject): List<YoutubeSubtitleChoice> {
    val choices = mutableListOf<YoutubeSubtitleChoice>()
    fun appendChoices(container: JSONObject?, auto: Boolean) {
        if (container == null) return
        container.keys().forEach { language ->
            val arr = container.optJSONArray(language) ?: return@forEach
            if (arr.length() == 0) return@forEach
            choices += YoutubeSubtitleChoice(
                label = if (auto) "$language (auto)" else language,
                languageCode = language,
                isAutoGenerated = auto
            )
        }
    }
    appendChoices(json.optJSONObject("subtitles"), false)
    appendChoices(json.optJSONObject("automatic_captions"), true)
    return choices.distinctBy { "${it.languageCode}:${it.isAutoGenerated}" }
}

fun parseYoutubeSubtitleListOutput(output: String): List<YoutubeSubtitleChoice> {
    val choices = mutableListOf<YoutubeSubtitleChoice>()
    var inSubtitleSection = false
    var automatic = false
    val languageCodePattern = Regex("""^[a-zA-Z]{2,3}(?:[-_][a-zA-Z0-9]+)*$""")

    output.lineSequence()
        .map { it.trim() }
        .filter { it.isNotBlank() }
        .forEach { line ->
            val lower = line.lowercase(Locale.US)
            when {
                lower.contains("available automatic captions") -> {
                    inSubtitleSection = true
                    automatic = true
                    return@forEach
                }
                lower.contains("available subtitles") -> {
                    inSubtitleSection = true
                    automatic = false
                    return@forEach
                }
                lower.startsWith("[info]") && !lower.contains("available") -> return@forEach
                lower.startsWith("language") || lower.startsWith("name") -> return@forEach
                !inSubtitleSection -> return@forEach
            }

            val code = line.split(Regex("""\s+""")).firstOrNull()
                ?.takeIf { languageCodePattern.matches(it) }
                ?: return@forEach
            choices += YoutubeSubtitleChoice(
                label = if (automatic) "$code (auto)" else code,
                languageCode = code,
                isAutoGenerated = automatic
            )
        }

    return choices.distinctBy { "${it.languageCode}:${it.isAutoGenerated}" }
}

private fun parseYoutubeFormats(json: JSONObject): List<YoutubeStreamFormat> {
    val formats = json.optJSONArray("formats") ?: JSONArray()
    return buildList {
        for (i in 0 until formats.length()) {
            val obj = formats.optJSONObject(i) ?: continue
            add(
                YoutubeStreamFormat(
                    formatId = obj.optString("format_id").takeIf { it.isNotBlank() },
                    formatNote = obj.optString("format_note").takeIf { it.isNotBlank() },
                    ext = obj.optString("ext").takeIf { it.isNotBlank() },
                    vcodec = obj.optString("vcodec").takeIf { it.isNotBlank() },
                    acodec = obj.optString("acodec").takeIf { it.isNotBlank() },
                    height = obj.optInt("height", 0),
                    tbr = obj.optDouble("tbr", 0.0).roundToInt(),
                    url = obj.optString("url").takeIf { it.isNotBlank() },
                    manifestUrl = obj.optString("manifest_url").takeIf { it.isNotBlank() },
                    protocol = obj.optString("protocol").takeIf { it.isNotBlank() }
                )
            )
        }
    }
}

private fun YoutubeStreamFormat.bestPlaybackUrl(): String? {
    val manifest = manifestUrl?.takeIf { it.startsWith("http", ignoreCase = true) }
    val directUrl = url?.takeIf { it.startsWith("http", ignoreCase = true) }
    val protocolValue = protocol.orEmpty().lowercase(Locale.US)
    return when {
        protocolValue.contains("m3u8") -> directUrl ?: manifest
        protocolValue.contains("dash") -> manifest ?: directUrl
        isVlcFriendlyVideoFormat() || isVlcFriendlyAudioFormat() -> directUrl ?: manifest
        else -> manifest ?: directUrl
    }
}

fun YoutubeStreamFormat.isVlcFriendlyVideoFormat(): Boolean {
    val codec = vcodec.orEmpty().lowercase(Locale.US)
    val audioCodec = acodec.orEmpty().lowercase(Locale.US)
    val extension = ext.orEmpty().lowercase(Locale.US)
    if (codec == "none" || audioCodec == "none") return false
    return extension == "mp4" &&
        (codec.startsWith("avc") || codec.startsWith("h264")) &&
        (audioCodec.startsWith("mp4a") || audioCodec.startsWith("aac"))
}

fun YoutubeStreamFormat.isVlcFriendlyAudioFormat(): Boolean {
    val codec = acodec.orEmpty().lowercase(Locale.US)
    val extension = ext.orEmpty().lowercase(Locale.US)
    val videoCodec = vcodec.orEmpty().lowercase(Locale.US)
    if (videoCodec != "none" || codec == "none") return false
    return extension == "m4a" || extension == "mp4" || codec.startsWith("mp4a") || codec.startsWith("aac")
}

private fun isVideoFile(file: File): Boolean {
    return file.extension.lowercase(Locale.US) in setOf("mp4", "mkv", "webm", "mov", "avi", "m4v")
}

data class CachedStreamUrl(val url: String, val expiresAtMillis: Long)

enum class StreamProvider { YouTube, Bilibili, Niconico, Other }

object StreamUrlCache {
    private val values = mutableMapOf<String, CachedStreamUrl>()
    fun get(key: String): CachedStreamUrl? = values[key]
    fun put(key: String, value: CachedStreamUrl) {
        values[key] = value
    }
    fun remove(key: String) {
        values.remove(key)
    }
}

fun cachedPlayableMediaUri(item: LibraryItem): String? {
    val sourceUrl = item.sourceUrl ?: return null
    return cachedResolvedStreamUrl(sourceUrl, item.formatId)
}

fun cachedResolvedStreamUrl(sourceUrl: String, formatId: String?): String? {
    val now = System.currentTimeMillis()
    val cached = StreamUrlCache.get(streamUrlCacheKey(sourceUrl, formatId))
        ?: return null
    if (cached.expiresAtMillis <= now) {
        StreamUrlCache.remove(streamUrlCacheKey(sourceUrl, formatId))
        return null
    }
    if (isYoutubeUrl(sourceUrl) && isExpiredYoutubeDirectStreamUrl(cached.url, now)) {
        StreamUrlCache.remove(streamUrlCacheKey(sourceUrl, formatId))
        return null
    }
    return cached.url
}

fun cacheResolvedStreamUrl(sourceUrl: String?, formatId: String?, streamUrl: String?) {
    val source = sourceUrl?.trim()?.takeIf { it.isNotBlank() } ?: return
    val stream = streamUrl?.trim()?.takeIf { it.startsWith("http", ignoreCase = true) } ?: return
    if (stream == source) return
    val now = System.currentTimeMillis()
    if (isYoutubeUrl(source) && isExpiredYoutubeDirectStreamUrl(stream, now)) return
    val provider = detectStreamProvider(source)
    val expiresAt = streamUrlCacheExpiryMs(provider, now, stream)
    StreamUrlCache.put(streamUrlCacheKey(source, formatId), CachedStreamUrl(stream, expiresAt))
}

private fun streamUrlCacheKey(sourceUrl: String, formatId: String?): String {
    val resolvedFormatId = formatId.takeUnless { isKnownYoutubeVideoOnlyFormatId(it) }
    return "stream_cache_${sourceUrl}_${resolvedFormatId.orEmpty()}"
}

fun detectStreamProvider(sourceUrl: String): StreamProvider = when {
    isYoutubeUrl(sourceUrl) -> StreamProvider.YouTube
    isBilibiliUrl(sourceUrl) -> StreamProvider.Bilibili
    isNiconicoUrl(sourceUrl) -> StreamProvider.Niconico
    else -> StreamProvider.Other
}

fun streamUrlCacheExpiryMs(provider: StreamProvider, nowMs: Long): Long {
    val ttl = when (provider) {
        StreamProvider.YouTube -> 4 * 60 * 60 * 1000L
        StreamProvider.Bilibili -> 2 * 60 * 60 * 1000L
        StreamProvider.Niconico -> 2 * 60 * 60 * 1000L
        StreamProvider.Other -> 30 * 60 * 1000L
    }
    return nowMs + ttl
}

private fun streamUrlCacheExpiryMs(provider: StreamProvider, nowMs: Long, streamUrl: String): Long {
    val defaultExpiry = streamUrlCacheExpiryMs(provider, nowMs)
    val directUrlExpiry = youtubeDirectStreamExpiryMs(streamUrl)?.minus(60_000L)
    return if (provider == StreamProvider.YouTube && directUrlExpiry != null) {
        minOf(defaultExpiry, directUrlExpiry)
    } else {
        defaultExpiry
    }
}

fun isExpiredYoutubeDirectStreamUrl(streamUrl: String, nowMs: Long = System.currentTimeMillis()): Boolean {
    val expiry = youtubeDirectStreamExpiryMs(streamUrl) ?: return false
    return expiry <= nowMs + 60_000L
}

private fun youtubeDirectStreamExpiryMs(streamUrl: String): Long? {
    val match = Regex("""[?&]expire=(\d+)""").find(streamUrl) ?: return null
    val seconds = match.groupValues.getOrNull(1)?.toLongOrNull() ?: return null
    return seconds * 1000L
}
